import { Device, Event, Alert, SystemStatus, User, Config } from './api';

export const MOCK_USER: User = {
    id: '1',
    name: 'Usuario',
    email: 'usuario@gmail.com',
    role: 'admin',
    createdAt: '2024-01-01T00:00:00Z',
};

export const MOCK_SYSTEM_STATUS: SystemStatus = {
    armed: true,
    state: 'armed',
    devicesOnline: 5,
    devicesTotal: 5,
    lastUpdated: new Date().toISOString(),
};

export const MOCK_DEVICES: Device[] = [
    {
        id: '1',
        name: 'Entrada Principal',
        type: 'camera',
        location: 'Entrada Principal',
        zone: 'exterior',
        status: 'online',
        resolution: 'HD 1080p',
        model: 'T3G-CAM-500',
        ip: '192.168.1.101',
        lastSeen: new Date().toISOString(),
    },
    {
        id: '2',
        name: 'Jardín Trasero',
        type: 'camera',
        location: 'Jardín Trasero',
        zone: 'exterior',
        status: 'online',
        resolution: 'HD 1080p',
        model: 'T3G-CAM-500',
        ip: '192.168.1.102',
        lastSeen: new Date().toISOString(),
    },
    {
        id: '3',
        name: 'Estacionamiento',
        type: 'camera',
        location: 'Estacionamiento',
        zone: 'exterior',
        status: 'online',
        resolution: 'HD 1080p',
        model: 'T3G-CAM-500',
        ip: '192.168.1.103',
        lastSeen: new Date().toISOString(),
    },
    {
        id: '4',
        name: 'Entrada Lateral',
        type: 'camera',
        location: 'Lateral Derecho',
        zone: 'exterior',
        status: 'online',
        resolution: 'HD 1080p',
        model: 'T3G-CAM-300',
        ip: '192.168.1.104',
        lastSeen: new Date().toISOString(),
    },
    {
        id: '5',
        name: 'Sensor Puerta',
        type: 'sensor',
        location: 'Puerta Principal',
        zone: 'interior',
        status: 'warning',
        batteryLevel: 15,
        model: 'T3G-SENS-100',
        lastSeen: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: '6',
        name: 'Alarma Principal',
        type: 'alarm',
        location: 'Sala',
        zone: 'interior',
        status: 'online',
        model: 'T3G-ALR-200',
        ip: '192.168.1.106',
        lastSeen: new Date().toISOString(),
    },
];

export const MOCK_EVENTS: Event[] = [
    {
        id: '1',
        type: 'alert',
        description: 'Movimiento detectado en zona restringida',
        device: 'Cámara 1',
        deviceId: '1',
        timestamp: '2025-11-07T14:32:15Z',
        hasRecording: true,
        acknowledged: false,
    },
    {
        id: '2',
        type: 'alert',
        description: 'Sensor de puerta activado',
        device: 'Sensor 2',
        deviceId: '5',
        timestamp: '2025-11-07T13:45:22Z',
        hasRecording: false,
        acknowledged: false,
    },
    {
        id: '3',
        type: 'system',
        description: 'Sistema armado correctamente',
        device: 'Sistema',
        timestamp: '2025-11-07T12:00:00Z',
        hasRecording: false,
        acknowledged: true,
    },
    {
        id: '4',
        type: 'alert',
        description: 'Movimiento detectado en entrada',
        device: 'Cámara 3',
        deviceId: '3',
        timestamp: '2025-11-07T10:23:11Z',
        hasRecording: true,
        acknowledged: true,
    },
    {
        id: '5',
        type: 'info',
        description: 'Actualización de firmware completada',
        device: 'Cámara 2',
        deviceId: '2',
        timestamp: '2025-11-07T09:15:30Z',
        hasRecording: true,
        acknowledged: true,
    },
    {
        id: '6',
        type: 'system',
        description: 'Sistema desarmado',
        device: 'Sistema',
        timestamp: '2025-11-07T08:00:00Z',
        hasRecording: false,
        acknowledged: true,
    },
    {
        id: '7',
        type: 'alert',
        description: 'Batería baja detectada',
        device: 'Sensor 1',
        deviceId: '5',
        timestamp: '2025-11-06T22:10:45Z',
        hasRecording: false,
        acknowledged: false,
    },
    {
        id: '8',
        type: 'info',
        description: 'Cámara 3 reconectada',
        device: 'Cámara 3',
        deviceId: '3',
        timestamp: '2025-11-06T21:30:00Z',
        hasRecording: false,
        acknowledged: true,
    },
];

export const MOCK_ALERTS: Alert[] = [
    {
        id: '1',
        type: 'motion',
        severity: 'high',
        message: 'Movimiento detectado en Entrada Principal',
        device: 'Cámara 1',
        timestamp: '2025-11-07T14:32:00Z',
        read: false,
    },
    {
        id: '2',
        type: 'system',
        severity: 'low',
        message: 'Sistema armado correctamente',
        device: 'Sistema',
        timestamp: '2025-11-07T12:00:00Z',
        read: true,
    },
    {
        id: '3',
        type: 'device',
        severity: 'medium',
        message: 'Cámara 3 reconectada',
        device: 'Cámara 3',
        timestamp: '2025-11-07T09:15:00Z',
        read: true,
    },
];

export const MOCK_CONFIG: Config = {
    notifications: {
        email: true,
        sms: true,
        push: true,
        motionAlerts: true,
        systemAlerts: true,
    },
    recording: {
        quality: 'FHD',
        duration: 30,
        retentionDays: 30,
        continuous: false,
        motionOnly: true,
    },
    security: {
        entryDelay: 30,
        exitDelay: 60,
        alarmDuration: 300,
        zones: [
            { id: '1', name: 'Exterior', armed: true, devices: ['1', '2', '3', '4'] },
            { id: '2', name: 'Interior', armed: true, devices: ['5', '6'] },
        ],
    },
};
